config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "callbacks" }
  
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: "application#home"

  resources :users, only: [:show] 

  resources :events 

  resources :events_users, only: [:new, :create, :destroy]
  
  resources :games do
    get :kid_friendly
    resources :plays, only: [:create, :update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_and_belongs_to_many :users

    validates :name, presence: true, uniqueness: true, length: {minimum: 3}

end

app/models/game.rb
class Game < ApplicationRecord
    has_many :plays
    has_many :users, through: :plays

    validates :name, presence: true, uniqueness: true

    scope :kid_friendly, -> {where("min_age < ?", "10")}


end

app/models/game_play.rb
class Play < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :game
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :games, through: :plays
  has_and_belongs_to_many :events

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid:auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  private

  # def to_param
  #   name
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def home
        if user_signed_in?
            redirect_to user_path(current_user)
        end
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    if @event.valid?
      current_user.events << @event
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.find_by_id(params[:id])
    if @event.users.include?(current_user)
      @attending = true
    else
      @attending = false
    end
  end

  def edit
    @event = Event.find_by_id(params[:id])
  end

  def update
    @event = Event.find_by_id(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def index
    @events = Event.all
  end

  def destroy
    event = Event.find_by_id(params[:id])
    event.destroy
    redirect_to user_path(current_user)
  end

  private

  def event_params
    params.require(:event).permit(:name, :date_time)
  end
end

app/controllers/game_users_controller.rb
class GameUsersController < ApplicationController
  def show
    
  end

  def edit
  end

  def update
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.save
    if @game.valid?
      current_user.games << @game
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def index
    @games = Game.all
    if @games.empty?
      redirect_to new_game_path
    end
  end

  def show
    @game = Game.find_by(id: params[:id])
  end

  def kid_friendly
    @games = Game.kid_friendly
    @kf = true
    render :index
  end

  def edit
    @game = Game.find_by(id: params[:id])
  end

  def update
    @game = Game.new(game_params)
    @game.save
    if @game.valid?
      current_user.games << @game
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def destroy
    game = Game.find_by(id: params[:id])
    game.destroy
  end

  private

  def game_params
    params.require(:game).permit(:name, :min_play_time, :max_play_time, :min_num_players, :max_num_players, :min_age, :max_age)
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  def update
    binding.pry
    play = Play.find(params[:id])
    @game = Game.find(params[:game_id])
    num = play.num_plays
    num = num + 1
    play.update(num_plays: num)
    play.save
    redirect_to game_path(@game)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
    @events = @user.events
    @games = @user.games.uniq
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/game_users_helper.rb
module GameUsersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/mechanisms_helper.rb
module MechanismsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
 
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for [@group, @event] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.datetime_select :date_time %>
    <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit <%= @event.name %>Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events</h1>

<% @events.each do |event| %>
<div>
    <%= link_to event.name, event_path(event) %></br>
    <%= event.date_time.to_formatted_s(:long_ordinal) %>
</div>
<% end %>
</br>
<div>
    <%= button_to "Create a New Event", new_event_path, method: "get" %>
</div>

app/views/events/new.html.erb
<h1>New Event Page</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

    <%= @event.date_time.to_formatted_s(:long_ordinal) %></br>
    </br>
    <% if current_user.events.include?(@event) %>
    <div>
        <%= button_to "Edit Event", edit_event_path(@event), method: "get" %>
        <%= button_to "Leave Event",  event_leave_path(@event), method: "get" %>
        <%= button_to "Delete Event", event_path(@event), method: "delete" %>
    </div>
    </br>
    <h3>Attending:</h3>
    <% @event.users.each do |user| %>
        <div><%= link_to user.name, user_path(user) %></div>
    <% end %>
    <h3>Available Games:</h3>
    <% @event.users.each do |user| %>
        <% user.games.each do |game| %>
            <div><%= link_to game.name, game_path(game) %></div>
        <% end %>
    <% end %>
<% else %>
    <div>
        <%= button_to "Join Event", event_join_path(@event), method: "get" %>
    </div>
<% end %>

app/views/games/_form.html.erb
<% if @game.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
 
    <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @game do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %></br>
    <%= f.label :min_play_time %>
    <%= f.text_field :min_play_time, placeholder: "in minutes" %>
    <%= f.label :max_play_time %>
    <%= f.text_field :max_play_time, placeholder: "in minutes" %></br>
    <%= f.label "Min # of Players" %>
    <%= f.text_field :min_num_players %>
    <%= f.label "Max # of Players" %>
    <%= f.text_field :max_num_players %></br>
    <%= f.label :min_age %>
    <%= f.text_field :min_age %>
    <%= f.label :max_age %>
    <%= f.text_field :max_age, placeholder: "enter '100' if no max"%></br>
    <%= f.submit %>
<% end %>

app/views/games/edit.html.erb
<h1>Edit "<i><%= @game.name %></i>"</h1>

<%= render 'form' %>

app/views/games/index.html.erb
<h1>All Games</h1>

<% if @kf == true %>
    <h2>Kid Friendly!</h2>
    <div><%= button_to "See All Games", games_path, method: "get" %></div>
<% else %>
    <div><%= button_to "See All Kid Friendly Games", game_kid_friendly_path(@games.first), method: "get" %></div>
<% end %>

<% @games.each do |game| %>
    <div><%= link_to game.name, game_path(game) %></div>
<% end %>

<div><%= button_to "Add a New Game", new_game_path, method: "get" %></div>

app/views/games/new.html.erb
<h1>Create New Game</h1>

<%= render 'form'%>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<% if @game.min_play_time || @game.max_play_time %>
    <h3>Play Time: <%= @game.min_play_time %> - <%= @game.max_play_time %> minutes</h4>
<% end %>
<% if @game.min_num_players || @game.max_num_players %>
<h3>Num of Players: <%= @game.min_num_players %> - <%= @game.max_num_players %></h4>
<% end %>
<% if @game.min_age || @game.max_age %>
<h3>Age Range: <%= @game.min_age %> - <%= @game.max_age %></h4>
<% end %>

<% if current_user.games.include?(@game)%>
    <h3>Game Plays:</h3>
    <% @game.plays.each do |play| %>
        <% if play.user_id == current_user.id%>
            <div><%= play.num_plays %></div>
            <div><%= button_to "Add a Game Play", game_play_path(@game, play), method: "patch" %></div>
        <% end %>
    <% end %>
    </br>
    </br>
    <div><%= button_to "Edit Game", edit_game_path(@game), method: "get" %></div>
    <div><%= button_to "Remove Game", game_path(@game), method: "delete" %></div>
<% else %>
    <div><%= button_to "Add Game", game_add_path(@game), method: "get" %></div>
<% end %>
</br>
<div><%= button_to "See All Games", games_path, method: "get" %></div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
</br>
<% if @user == current_user %>
    <h4>Your Events are:</h4>
    <% if !@events.empty? %>
        <% @events.each do |event| %>
            <div>
                <%= link_to event.name, event_path(event) %></br>
                <%= event.date_time.to_formatted_s(:long_ordinal) %></br>
            </div>
        <% end %>
    <% end %>
    <div>
        <%= button_to "Add New Event", new_event_path, method: "get" %>
    </div>
    <div>
        <%= button_to "See All Events", events_path, method: "get" %>
    </div>
<% end %>
</br>
<h4>Games:</h4>
<% if !@games.empty? %>
    <% @games.each do |game| %>
        <div><%= link_to game.name, game_path(game) %></div>
    <% end %>
<% elsif @user == current_user %>
    <div><%= button_to "Add a New Game", new_game_path, method: "get" %></div>
<% end %>
    <div><%= button_to "See All Games", games_path, method: "get" %></div>